# Generated by Django 3.2 on 2021-05-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Source Name')),
            ],
            options={
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('file', 'Text File'), ('video', 'Video'), ('v-url', 'Video URL'), ('url', 'URL')], max_length=100)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('content_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_category', to='Config.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_source', to='Config.source')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_tag', to='Config.tag')),
            ],
            options={
                'verbose_name': 'Data Entry',
                'verbose_name_plural': 'Data Entries',
            },
        ),
    ]
